
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, env } from "prisma/config";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
loadEnv({ path: path.resolve(__dirname, ".env") });

function resolveDatabaseUrl() {
  const baseUrl = env("DATABASE_URL");
  const explicitPort = process.env.DB_PORT || process.env.DB_PORT?.trim();

  if (!explicitPort) {
    return baseUrl;
  }

  try {
    const parsedUrl = new URL(baseUrl);
    parsedUrl.port = explicitPort;
    return parsedUrl.toString();
  } catch {
    return baseUrl;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
