'use client';

import { useState } from 'react';
import { Search } from 'lucide-react';

type OrderItem = { name?: string; quantity?: number; unitPrice?: number; price?: number };
type Order = { id: string; customerName?: string; customerEmail?: string | null; createdAt?: string; total?: number; status?: string; items?: OrderItem[] };
type Refund = { id: string; requestId: string; orderId: string; customerName: string; customerEmail?: string | null; reason: string; amount: number; status: string; requestedAt: string };

function formatDate(value?: string) { const date = value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '—'; }
function statusClass(status: string) { return status === 'DELIVERED' || status === 'APPROVED' ? 'bg-emerald-500/10 text-emerald-400' : status === 'CANCELLED' || status === 'REJECTED' ? 'bg-red-500/10 text-red-400' : 'bg-amber-500/10 text-amber-300'; }

export function OrdersView({ title, items }: { title: string; items: Order[] }) {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const pageSize = 10;
  const filtered = items.filter((order) => `${order.id} ${order.customerName ?? ''} ${order.customerEmail ?? ''} ${order.status ?? ''}`.toLowerCase().includes(query.toLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  return <div><div className="mb-5"><p className="text-xs uppercase tracking-[0.16em] text-sky-400">Orders</p><h1 className="mt-1 text-2xl font-bold">{title}</h1><p className="mt-2 text-sm text-slate-400">Live orders from the AromaCraft database.</p></div><div className="relative max-w-sm"><Search size={15} className="absolute left-3 top-2.5 text-slate-500" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search orders" className="w-full rounded-md border border-slate-600 bg-slate-800 py-2 pl-9 text-sm text-slate-100 outline-none" /></div><div className="mt-4 overflow-x-auto border border-slate-700 bg-slate-800"><table className="w-full min-w-215 text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Order ID</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Items</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th></tr></thead><tbody>{visible.map((order) => <tr key={order.id} className="border-b border-slate-700/70 align-top"><td className="px-4 py-3 font-medium text-slate-100">{order.id}</td><td className="px-4 py-3"><div className="text-slate-100">{order.customerName ?? 'Unknown customer'}</div>{order.customerEmail && <div className="text-xs text-slate-400">{order.customerEmail}</div>}</td><td className="max-w-64 px-4 py-3 text-slate-300">{order.items?.map((item) => `${item.name ?? 'Item'} × ${item.quantity ?? 0}`).join(', ') || 'No items'}</td><td className="px-4 py-3 text-slate-100">${Number(order.total ?? 0).toLocaleString()}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs ${statusClass(order.status ?? '')}`}>{(order.status ?? 'PENDING').replaceAll('_', ' ')}</span></td><td className="px-4 py-3 text-slate-300">{formatDate(order.createdAt)}</td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-sm text-slate-400">No orders match this view.</p>}</div><div className="mt-4 flex items-center justify-between text-sm text-slate-400"><span>Page {page} of {pages}</span><div className="flex gap-2"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded border border-slate-600 px-3 py-1.5 disabled:opacity-40">Previous</button><button type="button" disabled={page === pages} onClick={() => setPage((value) => value + 1)} className="rounded border border-slate-600 px-3 py-1.5 disabled:opacity-40">Next</button></div></div></div>;
}

export function RefundRequestsView({ initialItems }: { initialItems: Refund[] }) {
  const [items, setItems] = useState(initialItems); const [filter, setFilter] = useState('ALL'); const [message, setMessage] = useState('');
  const visible = filter === 'ALL' ? items : items.filter((item) => item.status === filter);
  async function decide(requestId: string, action: 'approve' | 'reject') { setMessage(''); const response = await fetch('/api/manager/refund-requests', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestId, action }) }); const body = await response.json(); if (!response.ok || body.success === false) { setMessage(body.error?.message ?? 'Unable to update refund request.'); return; } setItems((current) => current.map((item) => item.id === requestId ? { ...item, status: action === 'approve' ? 'APPROVED' : 'REJECTED' } : item)); }
  return <div><div className="mb-5"><p className="text-xs uppercase tracking-[0.16em] text-sky-400">Orders</p><h1 className="mt-1 text-2xl font-bold">Refund requests</h1><p className="mt-2 text-sm text-slate-400">Review and decide customer refund requests from the live database.</p></div><div className="flex flex-wrap items-center gap-3"><label className="text-sm text-slate-400">Status<select value={filter} onChange={(event) => setFilter(event.target.value)} className="ml-2 rounded-md border border-slate-600 bg-slate-800 px-3 py-2 text-sm text-slate-100"><option value="ALL">All</option><option value="REQUESTED">Requested</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label>{message && <p className="text-sm text-red-400">{message}</p>}</div><div className="mt-4 overflow-x-auto border border-slate-700 bg-slate-800"><table className="w-full min-w-215 text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Order ID</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Reason</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Requested</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id} className="border-b border-slate-700/70 align-top"><td className="px-4 py-3 font-medium text-slate-100">{item.orderId}</td><td className="px-4 py-3"><div className="text-slate-100">{item.customerName}</div>{item.customerEmail && <div className="text-xs text-slate-400">{item.customerEmail}</div>}</td><td className="max-w-64 px-4 py-3 text-slate-300">{item.reason}</td><td className="px-4 py-3">${item.amount.toLocaleString()}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs ${statusClass(item.status)}`}>{item.status}</span></td><td className="px-4 py-3">{formatDate(item.requestedAt)}</td><td className="px-4 py-3">{item.status === 'REQUESTED' ? <div className="flex gap-2"><button type="button" onClick={() => void decide(item.id, 'approve')} className="text-emerald-400 hover:text-emerald-300">Approve</button><button type="button" onClick={() => void decide(item.id, 'reject')} className="text-red-400 hover:text-red-300">Reject</button></div> : <span className="text-slate-500">Decided</span>}</td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-sm text-slate-400">No refund requests match this filter.</p>}</div></div>;
}
