'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowRight, Download } from 'lucide-react';

const colors = ['#72b58d', '#5ea8d6', '#e0a64d', '#d88989', '#9d8ac7', '#7db7ae'];
export type RevenueData = { series: Array<{ label: string; revenue: number; target: number }>; totalRevenue: number; averageOrderValue: number; revenueVsTarget: number | null; totalOrders: number };
export type BrandData = { brands: Array<{ name: string; unitsSold: number; revenue: number; percentage: number }>; totalRevenue: number };
export type ProductData = { items: Array<{ id: number; name: string; brand: string; unitsSold: number; revenue: number }>; totalRevenue: number };
export type CustomerData = { series: Array<{ label: string; newCustomers: number }>; totalCustomers: number; newThisMonth: number; growthRate: number | null };

type ReportKind = 'revenue' | 'sales-by-brand' | 'sales-by-product' | 'customer-growth';

function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value); }
function downloadCsv(filename: string, headers: string[], rows: Array<Array<string | number>>) {
  const csv = [headers, ...rows].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n');
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
}
function ExportButton({ kind, data }: { kind: ReportKind; data: RevenueData | BrandData | ProductData | CustomerData }) {
  const exportData = () => {
    if (kind === 'revenue') { const report = data as RevenueData; downloadCsv('revenue-report.csv', ['Month', 'Revenue', 'Target'], report.series.map((row) => [row.label, row.revenue, row.target])); }
    if (kind === 'sales-by-brand') { const report = data as BrandData; downloadCsv('sales-by-brand.csv', ['Brand', 'Units sold', 'Revenue', 'Percentage'], report.brands.map((row) => [row.name, row.unitsSold, row.revenue, `${row.percentage}%`])); }
    if (kind === 'sales-by-product') { const report = data as ProductData; downloadCsv('sales-by-product.csv', ['Product', 'Brand', 'Units sold', 'Revenue'], report.items.map((row) => [row.name, row.brand, row.unitsSold, row.revenue])); }
    if (kind === 'customer-growth') { const report = data as CustomerData; downloadCsv('customer-growth.csv', ['Month', 'New customers'], report.series.map((row) => [row.label, row.newCustomers])); }
  };
  return <button type="button" onClick={exportData} className="inline-flex items-center gap-2 rounded-md border border-slate-600 px-3 py-2 text-sm font-medium text-slate-200 hover:border-sky-400 hover:text-sky-300"><Download size={15} /> Export to CSV</button>;
}
function Kpi({ label, value, detail }: { label: string; value: string; detail?: string }) { return <div className="border-l-2 border-sky-400 bg-slate-800 p-4"><div className="text-xs uppercase tracking-[0.12em] text-slate-400">{label}</div><div className="mt-3 text-2xl font-bold text-slate-100">{value}</div>{detail && <div className="mt-1 text-xs text-slate-500">{detail}</div>}</div>; }
function EmptyChart({ message = 'No report data is available for this period.' }) { return <div className="flex h-full items-center justify-center text-sm text-slate-500">{message}</div>; }
function ReportShell({ title, description, kind, data, children }: { title: string; description: string; kind: ReportKind; data: RevenueData | BrandData | ProductData | CustomerData; children: React.ReactNode }) { return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-sky-400">Manager portal</p><h1 className="mt-1 text-2xl font-bold capitalize">{title}</h1><p className="mt-2 text-sm text-slate-400">{description}</p></div><ExportButton kind={kind} data={data} /></div>{children}</div>; }

export function RevenueReportView({ data }: { data: RevenueData }) { return <ReportShell title="Revenue report" description="Monthly revenue performance from completed and active orders." kind="revenue" data={data}><div className="mt-6 grid gap-3 sm:grid-cols-3"><Kpi label="Revenue this month" value={money(data.totalRevenue)} /><Kpi label="Average order value" value={money(data.averageOrderValue)} /><Kpi label="Revenue vs target" value={data.revenueVsTarget === null ? 'Not configured' : `${data.revenueVsTarget}%`} detail="Targets are managed separately" /></div><section className="mt-5 border border-slate-700 bg-slate-800 p-5"><h2 className="font-semibold">Revenue over the last 12 months</h2><div className="mt-5 h-80">{data.series.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={data.series}><XAxis dataKey="label" tickLine={false} axisLine={false} stroke="#94a3b8" /><YAxis tickLine={false} axisLine={false} stroke="#94a3b8" tickFormatter={(value) => `$${Number(value) / 1000}k`} /><Tooltip formatter={(value) => money(Number(value))} /><Line type="monotone" dataKey="revenue" stroke="#72b58d" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer> : <EmptyChart />}</div></section></ReportShell>; }

export function BrandReportView({ data }: { data: BrandData }) { return <ReportShell title="Sales by brand" description="Units and revenue contribution across every product brand." kind="sales-by-brand" data={data}><section className="mt-6 border border-slate-700 bg-slate-800 p-5"><h2 className="font-semibold">Revenue share</h2><div className="mt-5 h-80">{data.brands.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.brands} dataKey="revenue" nameKey="name" innerRadius={75} outerRadius={115} paddingAngle={2}>{data.brands.map((brand, index) => <Cell key={brand.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip formatter={(value) => money(Number(value))} /></PieChart></ResponsiveContainer> : <EmptyChart />}</div></section><div className="mt-5 overflow-x-auto border border-slate-700 bg-slate-800"><table className="w-full min-w-140 text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Brand</th><th className="px-4 py-3">Units sold</th><th className="px-4 py-3">Revenue</th><th className="px-4 py-3">Share</th></tr></thead><tbody>{data.brands.map((brand) => <tr key={brand.name} className="border-b border-slate-700/70"><td className="px-4 py-3 font-medium text-slate-100">{brand.name}</td><td className="px-4 py-3">{brand.unitsSold.toLocaleString()}</td><td className="px-4 py-3">{money(brand.revenue)}</td><td className="px-4 py-3">{brand.percentage}%</td></tr>)}</tbody></table>{!data.brands.length && <EmptyChart />}</div></ReportShell>; }

export function ProductReportView({ data }: { data: ProductData }) { const [page, setPage] = useState(1); const pageSize = 10; const pages = Math.max(1, Math.ceil(data.items.length / pageSize)); const items = data.items.slice((page - 1) * pageSize, page * pageSize); return <ReportShell title="Sales by product" description="Best-selling products ranked by units and generated revenue." kind="sales-by-product" data={data}><section className="mt-6 border border-slate-700 bg-slate-800 p-5"><h2 className="font-semibold">Top products</h2><div className="mt-4 h-64">{data.items.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data.items.slice(0, 10)} layout="vertical" margin={{ left: 24 }}><XAxis type="number" stroke="#94a3b8" /><YAxis type="category" dataKey="name" width={120} stroke="#94a3b8" tick={{ fontSize: 12 }} /><Tooltip formatter={(value) => money(Number(value))} /><Bar dataKey="revenue" fill="#5ea8d6" radius={[0, 3, 3, 0]} /></BarChart></ResponsiveContainer> : <EmptyChart />}</div></section><div className="mt-5 overflow-x-auto border border-slate-700 bg-slate-800"><table className="w-full min-w-160 text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Brand</th><th className="px-4 py-3">Units sold</th><th className="px-4 py-3">Total revenue</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-slate-700/70"><td className="px-4 py-3 font-medium text-slate-100">{item.name}</td><td className="px-4 py-3">{item.brand}</td><td className="px-4 py-3">{item.unitsSold.toLocaleString()}</td><td className="px-4 py-3">{money(item.revenue)}</td></tr>)}</tbody></table>{!data.items.length && <EmptyChart />}</div><div className="mt-4 flex items-center justify-between text-sm text-slate-400"><span>Page {page} of {pages}</span><div className="flex gap-2"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded border border-slate-600 px-3 py-1.5 disabled:opacity-40">Previous</button><button type="button" disabled={page === pages} onClick={() => setPage((value) => value + 1)} className="rounded border border-slate-600 px-3 py-1.5 disabled:opacity-40">Next</button></div></div></ReportShell>; }

export function CustomerGrowthView({ data }: { data: CustomerData }) { return <ReportShell title="Customer growth" description="New customer registrations and total active customer base." kind="customer-growth" data={data}><div className="mt-6 grid gap-3 sm:grid-cols-3"><Kpi label="Total customers" value={data.totalCustomers.toLocaleString()} /><Kpi label="New this month" value={data.newThisMonth.toLocaleString()} /><Kpi label="Growth rate" value={data.growthRate === null ? 'Not enough data' : `${data.growthRate}%`} /></div><section className="mt-5 border border-slate-700 bg-slate-800 p-5"><h2 className="font-semibold">New customers over the last 12 months</h2><div className="mt-5 h-80">{data.series.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.series}><XAxis dataKey="label" tickLine={false} axisLine={false} stroke="#94a3b8" /><YAxis allowDecimals={false} tickLine={false} axisLine={false} stroke="#94a3b8" /><Tooltip /><Area type="monotone" dataKey="newCustomers" stroke="#e0a64d" fill="#e0a64d" fillOpacity={0.2} strokeWidth={2} /></AreaChart></ResponsiveContainer> : <EmptyChart />}</div></section></ReportShell>; }

export function ReportsOverviewView({ data }: { data: { totalRevenue?: number; totalOrders?: number; totalCustomers?: number; newUsersThisMonth?: number; topBrand?: string } }) { const router = useRouter(); const revenue = useReportData<RevenueData>('/api/manager/reports/revenue').data; const customers = useReportData<CustomerData>('/api/manager/reports/customer-growth').data; const brands = useReportData<BrandData>('/api/manager/reports/sales-by-brand').data; const links = [{ label: 'Revenue report', slug: 'revenue-report', detail: 'Monthly performance and targets' }, { label: 'Sales by product', slug: 'sales-by-product', detail: 'Units and product revenue' }, { label: 'Sales by brand', slug: 'sales-by-brand', detail: 'Share by brand' }, { label: 'Customer growth', slug: 'customer-growth', detail: 'New registrations over time' }]; return <div><div><p className="text-xs uppercase tracking-[0.16em] text-sky-400">Manager portal</p><h1 className="mt-1 text-2xl font-bold">Reports &amp; Analytics</h1><p className="mt-2 text-sm text-slate-400">A live view of the business metrics that matter most.</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Revenue this month" value={money(revenue?.totalRevenue ?? data.totalRevenue ?? 0)} /><Kpi label="Orders this month" value={String(revenue?.totalOrders ?? data.totalOrders ?? 0)} /><Kpi label="New customers" value={String(customers?.newThisMonth ?? data.newUsersThisMonth ?? 0)} detail="Registered this month" /><Kpi label="Top selling brand" value={brands?.brands[0]?.name ?? data.topBrand ?? 'No sales yet'} /></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{links.map((link) => <button type="button" key={link.slug} onClick={() => router.push(`/dashboard/manager/reports-analytics/${link.slug}`)} className="flex items-center justify-between border border-slate-700 bg-slate-800 p-5 text-left hover:border-sky-400"><span><span className="block font-semibold text-slate-100">{link.label}</span><span className="mt-1 block text-sm text-slate-400">{link.detail}</span></span><ArrowRight size={18} className="text-sky-400" /></button>)}</div></div>; }

export function useReportData<T>(endpoint: string) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); useEffect(() => { const controller = new AbortController(); fetch(endpoint, { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok || body.ok === false) throw new Error(body.error?.message ?? 'Unable to load report'); setData(body.data ?? body); }).catch((reason: unknown) => { if (reason instanceof Error && reason.name !== 'AbortError') setError(reason.message); }); return () => controller.abort(); }, [endpoint]); return { data, error }; }
